// pertemuan-26-27-deployment-backend-frontend/angular/src/app/components/login-form/login-form.component.ts
// Mini Project - Pertemuan 23-24-25: Login dari SPA & menyimpan token JWT
// TODO 2: lengkapi AuthService.login() (lihat services/auth.service.ts) dan onSubmit() di bawah ini.

import { Component, EventEmitter, Output, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login-form.component.html',
})
export class LoginFormComponent {
  private authService = inject(AuthService);

  @Output() loginBerhasil = new EventEmitter<void>();

  username = '';
  password = '';
  error = '';

  onSubmit() {
    this.error = '';
    // TODO: setelah AuthService.login() lengkap, panggil:
    // this.authService.login(this.username, this.password).subscribe({
    //   next: (res) => {
    //     localStorage.setItem('token', res.token);
    //     this.loginBerhasil.emit();
    //   },
    //   error: () => { this.error = 'Username/password salah'; },
    // });
  }
}

// pertemuan-23-24-25-konsumsi-api-asinkron-jwt-spa/react/src/components/LoginForm.jsx
// Mini Project - Pertemuan 23-24-25: Login dari SPA & menyimpan token JWT
// TODO 2: lengkapi handleSubmit() di bawah ini.

import { useState } from "react";
import api from "../api/axiosInstance";

function LoginForm({ onLoginBerhasil }) {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  async function handleSubmit(e) {
    e.preventDefault();
    setError("");
    // TODO: panggil api.post('/auth/login', { username, password }) di dalam try/catch
    // TODO: jika berhasil, simpan token dengan localStorage.setItem('token', res.data.token)
    // TODO: panggil onLoginBerhasil()
    // TODO: jika gagal (catch), setError('Username/password salah')
  }

  return (
    <form className="login-form" onSubmit={handleSubmit}>
      <input
        placeholder="Username"
        value={username}
        onChange={(e) => setUsername(e.target.value)}
      />
      <input
        type="password"
        placeholder="Password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
      />
      <button type="submit">Login</button>
      {error && <span className="error">{error}</span>}
    </form>
  );
}

export default LoginForm;
