// pertemuan-26-27-deployment-backend-frontend/react/src/App.jsx
// Mini Project - Pertemuan 23-24-25: Konsumsi API sungguhan (Axios) & Autentikasi JWT
// Component tree (sudah lengkap dari Pertemuan 17-22): App (state) -> PageHeader, LoginForm|MahasiswaForm, SearchBar, MahasiswaList -> MahasiswaCard
// TODO 3: lengkapi pengambilan data (GET) dan pengiriman data (POST) di bawah ini.

import { useEffect, useState } from "react";
import "./App.css";
import api from "./api/axiosInstance";
import PageHeader from "./components/PageHeader";
import SearchBar from "./components/SearchBar";
import MahasiswaForm from "./components/MahasiswaForm";
import MahasiswaList from "./components/MahasiswaList";
import LoginForm from "./components/LoginForm";

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;

function App() {
  const [mahasiswa, setMahasiswa] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [keyword, setKeyword] = useState("");
  const [isLoggedIn, setIsLoggedIn] = useState(!!localStorage.getItem("token"));

  useEffect(() => {
    // TODO: panggil api.get('/mahasiswa')
    // TODO: .then((res) => setMahasiswa(res.data.data))
    // TODO: .catch(() => setError('Gagal memuat data mahasiswa'))
    // TODO: .finally(() => setLoading(false))
  }, []);

  async function handleTambah(mahasiswaBaru) {
    // TODO: bungkus dengan try/catch
    // TODO: const res = await api.post('/mahasiswa', mahasiswaBaru)
    // TODO: setMahasiswa((prev) => [...prev, res.data])
    // TODO: pada catch, tampilkan alert('Gagal menambah data (pastikan Anda sudah login)')
  }

  function handleLogout() {
    localStorage.removeItem("token");
    setIsLoggedIn(false);
  }

  const mahasiswaTersaring = mahasiswa.filter((m) =>
    m.nama.toLowerCase().includes(keyword.toLowerCase())
  );

  return (
    <div className="app">
      <PageHeader judul="Daftar Mahasiswa" />

      {isLoggedIn ? (
        <>
          <MahasiswaForm onTambah={handleTambah} />
          <button className="logout-button" onClick={handleLogout}>
            Logout
          </button>
        </>
      ) : (
        <LoginForm onLoginBerhasil={() => setIsLoggedIn(true)} />
      )}

      <SearchBar keyword={keyword} onSearch={setKeyword} />

      {loading && <p>Memuat...</p>}
      {error && <p className="error">{error}</p>}
      {!loading && !error && <MahasiswaList mahasiswa={mahasiswaTersaring} />}

      <footer className="env-footer">Terhubung ke: {API_BASE_URL}</footer>
    </div>
  );
}

export default App;

// pertemuan-23-24-25-konsumsi-api-asinkron-jwt-spa/angular/src/app/app.component.ts
// Mini Project - Pertemuan 23-24-25: Konsumsi API sungguhan (HttpClient) & Autentikasi JWT
// Component tree (sudah lengkap dari Pertemuan 17-22): AppComponent (state) -> PageHeader, LoginForm|MahasiswaForm, SearchBar, MahasiswaList -> MahasiswaCard
// TODO 5: lengkapi ngOnInit() (GET) dan onTambah() (POST) di bawah ini.

import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PageHeaderComponent } from './components/page-header/page-header.component';
import { SearchBarComponent } from './components/search-bar/search-bar.component';
import { MahasiswaFormComponent } from './components/mahasiswa-form/mahasiswa-form.component';
import { MahasiswaListComponent } from './components/mahasiswa-list/mahasiswa-list.component';
import { LoginFormComponent } from './components/login-form/login-form.component';
import { MahasiswaService } from './services/mahasiswa.service';
import { AuthService } from './services/auth.service';
import { Mahasiswa } from './mahasiswa.model';
import { environment } from '../environments/environment';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    PageHeaderComponent,
    SearchBarComponent,
    MahasiswaFormComponent,
    MahasiswaListComponent,
    LoginFormComponent,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent implements OnInit {
  private mahasiswaService = inject(MahasiswaService);
  private authService = inject(AuthService);

  apiBaseUrl = environment.apiBaseUrl;
  keyword = '';
  mahasiswa: Mahasiswa[] = [];
  loading = true;
  error = '';
  isLoggedIn = this.authService.isLoggedIn();

  ngOnInit() {
    // TODO: panggil this.mahasiswaService.getAll().subscribe({
    //   next: (res) => { this.mahasiswa = res.data; this.loading = false; },
    //   error: () => { this.error = 'Gagal memuat data mahasiswa'; this.loading = false; },
    // });
  }

  get mahasiswaTersaring(): Mahasiswa[] {
    return this.mahasiswa.filter((m) =>
      m.nama.toLowerCase().includes(this.keyword.toLowerCase())
    );
  }

  onSearch(keyword: string) {
    this.keyword = keyword;
  }

  onTambah(mahasiswaBaru: { nama: string; nim: string }) {
    // TODO: panggil this.mahasiswaService.create(mahasiswaBaru).subscribe({
    //   next: (res) => { this.mahasiswa = [...this.mahasiswa, res]; },
    //   error: () => { alert('Gagal menambah data (pastikan Anda sudah login)'); },
    // });
  }

  onLogout() {
    this.authService.logout();
    this.isLoggedIn = false;
  }
}
