// pertemuan-19-20-build-tools-cli-spa/angular/src/app/components/search-bar/search-bar.component.ts
// Mini Project - Pertemuan 19-20: Komponen anak, mengirim event ke induk lewat @Output() (sudah lengkap dari Pertemuan 17-18)

import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-search-bar',
  standalone: true,
  templateUrl: './search-bar.component.html',
})
export class SearchBarComponent {
  @Input() keyword = '';
  @Output() search = new EventEmitter<string>();

  onInput(event: Event) {
    const value = (event.target as HTMLInputElement).value;
    this.search.emit(value);
  }
}

// pertemuan-21-22-form-validasi-spa/react/src/components/SearchBar.jsx
// Mini Project - Pertemuan 21-22: Komponen anak yang mengirim event ke induk (sudah lengkap dari Pertemuan 17-18)

function SearchBar({ keyword, onSearch }) {
  return (
    <input
      className="search-bar"
      type="text"
      placeholder="Cari nama mahasiswa..."
      value={keyword}
      onChange={(e) => onSearch(e.target.value)}
    />
  );
}

export default SearchBar;
